# let's implement a simple, mock relational DB
# need to support
# projection (subset of columns)
# selection (subset of rows), equality, inequality (basic filters)
# limits (return the first N rows of a query)
# sorting (in memory, ascending or descending)
# for now, run the queries over test data that is already in memory i.e. a hand-coded list of "rows". We will implement heap files and an index later.


# the return for this should be an iterator where each operation is a linked list. Each node will store it's own state, and provide a next() method.
# the next method will yield the next row of the query one by one.
# importantly, you can assume that queries are already parsed.


class MemoryScan(object):
    """
    Yield all records from the given "table" in memory.

    This is really just for testing... in the future our scan nodes
    will read from disk.
    """
    def __init__(self, table):
        self.table = table
        self.idx = 0

    def __next__(self):
        if self.idx >= len(self.table):
            return None

        x = self.table[self.idx]
        self.idx += 1
        return x


class Projection(object):
    """
    Map the child records using the given map function, e.g. to return a subset
    of the fields.
    """
    def __init__(self, proj):
        self.proj = proj
        self.child = None
    
    def __next__(self):
        if self.child is None:
            return None
        x = next(self.child)
        if x:
            return self.proj(x)
        return None

class Selection(object):
    """
    Filter the child records using the given predicate function.

    Yes it's confusing to call this "selection" as it's unrelated to SELECT in
    SQL, and is more like the WHERE clause. We keep the naming to be consistent
    with the literature.
    """
    def __init__(self, predicate):
        self.predicate = predicate
        self.child = None
    def __next__(self):
        if self.child is None:
            return None
        x = next(self.child)
        while x:
            if self.predicate(x):
                return x
            x = next(self.child)
        return None

class Limit(object):
    """
    Return only as many as the limit, then stop
    """
    def __init__(self, n):
        self.n = n
        self.child = None
        self.curr = 0
    
    def __next__(self):
        if self.child is None:
            return None
        x = next(self.child)
        if x:
            if self.curr < self.n:
                self.curr += 1
                return x
        return None

class Sort(object):
    """
    Sort based on the given key function
    """
    def __init__(self, key, desc=False):
        self.key = key
        self.desc = desc
        self.child = None
        self.it = None
    
    def construct_iter(self):
        if self.child is None:
            return None
        res = []
        x = next(self.child)
        while x:
            res.append(x)
            x = next(self.child)
        if not res:
            return None
        return iter(sorted(res, key=self.key, reverse = self.desc))
        
    def __next__(self):
        if not self.it:
            self.it = self.construct_iter()
        try:
            x = next(self.it)
        except StopIteration:
            return None
        return x
def Q(*nodes):
    """
    Construct a linked list of executor nodes from the given arguments,
    starting with a root node, and adding references to each child
    """
    ns = iter(nodes)
    parent = root = next(ns)
    for n in ns:
        parent.child = n
        parent = n
    return root


def run(q):
    """
    Run the given query to completion by calling `next` on the (presumed) root
    """
    while True:
        x = next(q)
        if x is None:
            break
        yield x


if __name__ == '__main__':
    # Test data generated by Claude and probably not accurate!
    birds = (
        ('amerob', 'American Robin', 0.077, True),
        ('baleag', 'Bald Eagle', 4.74, True),
        ('eursta', 'European Starling', 0.082, True),
        ('barswa', 'Barn Swallow', 0.019, True),
        ('ostric1', 'Ostrich', 104.0, False),
        ('emppen1', 'Emperor Penguin', 23.0, False),
        ('rufhum', 'Rufous Hummingbird', 0.0034, True),
        ('comrav', 'Common Raven', 1.2, True),
        ('wanalb', 'Wandering Albatross', 8.5, False),
        ('norcar', 'Northern Cardinal', 0.045, True)
    )
    schema = (
        ('id', str),
        ('name', str),
        ('weight', float),
        ('in_us', bool),
    )

    # test a simple scan
    assert tuple(run(Q(
        Projection(lambda x: (x[0],)),
        Selection(lambda x: not x[3]),
        MemoryScan(birds)
    ))) == (
        ('ostric1',),
        ('emppen1',),
        ('wanalb',),
    ), f"Projection and Selection failed. {tuple(run(Q(Projection(lambda x: (x[0],)), Selection(lambda x: not x[3]), MemoryScan(birds))))}"
    
    # # id and weight of 3 heaviest birds
    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Limit(3),
        Sort(lambda x: x[2], desc=True),
        MemoryScan(birds),
    ))) == (
        ('ostric1', 104.0),
        ('emppen1', 23.0),
        ('wanalb', 8.5),
    )
    # try a few much harder cases, nested filter etc.
    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Selection(lambda x: x[2] > 10),
        MemoryScan(birds),
    ))) == (
        ('ostric1', 104.0),
        ('emppen1', 23.0),
    )

    # try a few much harder cases, nested filter etc.
    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Selection(lambda x: x[2] > 10),
        MemoryScan(birds),
    ))) == (
        ('ostric1', 104.0),
        ('emppen1', 23.0),
    )

    # nested selection
    # Original two asserts
    assert tuple(run(Q(
        Projection(lambda x: (x[0],)),
        Selection(lambda x: not x[3]),
        MemoryScan(birds)
    ))) == (
        ('ostric1',),
        ('emppen1',),
        ('wanalb',),
    )

    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Limit(3),
        Sort(lambda x: x[2], desc=True),
        MemoryScan(birds),
    ))) == (
        ('ostric1', 104.0),
        ('emppen1', 23.0),
        ('wanalb', 8.5),
    )

    # New asserts testing different combinations
    # Get names of 2 lightest US birds
    assert tuple(run(Q(
        Projection(lambda x: (x[1],)),
        Limit(2),
        Sort(lambda x: x[2]),  # sort by weight ascending
        Selection(lambda x: x[3]),  # US birds only
        MemoryScan(birds),
    ))) == (
        ('Rufous Hummingbird',),
        ('Barn Swallow',)
    )

    # Get all birds over 1kg (>1.0), sorted by name
    assert tuple(run(Q(
        Projection(lambda x: (x[1], x[2])),
        Sort(lambda x: x[1]),  # sort by name
        Selection(lambda x: x[2] > 1.0),
        MemoryScan(birds),
    ))) == (
        ('Bald Eagle', 4.74),
        ('Common Raven', 1.2),
        ('Emperor Penguin', 23.0),
        ('Ostrich', 104.0),
        ('Wandering Albatross', 8.5),
    )

    # Get IDs of the 2 heaviest non-US birds
    assert tuple(run(Q(
        Projection(lambda x: (x[0],)),
        Limit(2),
        Sort(lambda x: x[2], desc=True),
        Selection(lambda x: not x[3]),  # non-US birds
        MemoryScan(birds),
    ))) == (
        ('ostric1',),
        ('emppen1',),
    )


    print('ok')

